version: '3.9'

services:
  general-db:
    image: postgres
    mem_limit: 200 M
    environment:
      POSTGRES_USER: bank_app
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: orders
    networks:
      - backend
    volumes:
      - general_data:/var/lib/postgresql/data
    ports:
      - "5437:5432"

volumes:
  general_data:

networks:
  backend: